# Google Cloud Build configuration for Next.js frontend
steps:
  # Install dependencies
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'frontend'

  # Run tests
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['run', 'test:ci']
    dir: 'frontend'
    env:
      - 'CI=true'

  # Run quality checks
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['run', 'quality']
    dir: 'frontend'

  # Build the application
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'NODE_ENV=production'
      - 'NEXT_PUBLIC_API_URL=${_API_URL}'
      - 'NEXT_PUBLIC_BASE_URL=${_BASE_URL}'
      - 'NEXT_PUBLIC_ENVIRONMENT=production'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/pos-qr-frontend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/pos-qr-frontend:latest',
      '-f', 'frontend/Dockerfile',
      'frontend'
    ]

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pos-qr-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pos-qr-frontend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'pos-qr-frontend',
      '--image', 'gcr.io/$PROJECT_ID/pos-qr-frontend:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--set-env-vars', 'NODE_ENV=production,NEXT_PUBLIC_API_URL=${_API_URL},NEXT_PUBLIC_BASE_URL=${_BASE_URL}'
    ]

# Substitution variables
substitutions:
  _REGION: 'asia-northeast1'
  _API_URL: 'https://your-api-domain.com'
  _BASE_URL: 'https://your-frontend-domain.com'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s'